;; This buffer is for text that is not saved, and for Lisp evaluation.
;; To create a file, visit it with C-x C-f and enter text in its buffer.

SELECT COUNT(PATRON.PATRONID) AS PATRONCOUNT, BTY.BTYCODE, PATRON.REGDATE AS REGDATE, 
BRANCH.BRANCHCODE AS DEFAULTBRANCH
FROM CARLREPORTS_PATRON_V2 AS PATRON INNER JOIN CARLREPORTS_BTY_V2 BTY ON PATRON.BTY=BTY.BTYNUMBER INNER JOIN CARLREPORTS_BRANCH_V2 AS BRANCH 
ON PATRON.DEFAULTBRANCH = BRANCH.BRANCHNUMBER
WHERE BTY.BTYCODE NOT IN ('GRAD','ILL','INST','LIBUSE','STFBRW','STUDNT','TEMP')
;; AND REGDATE  BETWEEN (SYSDATE,'MM')) AND SYSDATE
GROUP BY BTY.BTYCODE, PATRON.REGDATE), BRANCH.BRANCHCODE
ORDER BY REGDATE DESC, BRANCH.BRANCHCODE ASC ;
