SELECT
  DISTINCT
  s.client_version
FROM
  v$session_connect_info s
WHERE
  s.sid = SYS_CONTEXT('USERENV', 'SID');
  
select * from bbibmap_v2 bib where upper(title) like '%TABLET%KIT%';

SELECT VALUE AS DATABASE_CHARACTER_SET
FROM NLS_DATABASE_PARAMETERS
WHERE PARAMETER = 'NLS_CHARACTERSET'

SELECT VALUE AS DATABASE_SORT
FROM NLS_DATABASE_PARAMETERS
WHERE PARAMETER = 'NLS_SORT'